var VTH = VTH || {};
VTH.towns = {
    addison: 'Addison',
    bridport: 'Bridport',
    bristol: 'Bristol',
    cornwall: 'Cornwall',
    ferrisburg: 'Ferrisburg',
    goshen: 'Goshen',
    granville: 'Granville',
    hancock: 'Hancock',
    leicester: 'Leicester',
    lincoln: 'Lincoln',
    middlebury: 'Middlebury',
    monkton: 'Monkton',
    new_haven: 'New Haven',
    orwell: 'Orwell',
    panton: 'Panton',
    ripton: 'Ripton',
    salisbury: 'Salisbury',
    shoreham: 'Shoreham',
    starksboro: 'Starksboro',
    vergennes: 'Vergennes',
    waltham: 'Waltham',
    weybridge: 'Weybridge',
    whiting: 'Whiting',
    arlington: 'Arlington',
    bennington: 'Bennington',
    dorset: 'Dorset',
    glastenbury: 'Glastenbury',
    landgrove: 'Landgrove',
    manchester: 'Manchester',
    peru: 'Peru',
    pownal: 'Pownal',
    readsboro: 'Readsboro',
    rupert: 'Rupert',
    sandgate: 'Sandgate',
    searsburg: 'Searsburg',
    shaftsbury: 'Shaftsbury',
    stamford: 'Stamford',
    sunderland: 'Sunderland',
    winhall: 'Winhall',
    woodford: 'Woodford',
    barnet: 'Barnet',
    burke: 'Burke',
    danville: 'Danville',
    groton: 'Groton',
    hardwick: 'Hardwick',
    kirby: 'Kirby',
    lyndon: 'Lyndon',
    newark: 'Newark',
    peacham: 'Peacham',
    ryegate: 'Ryegate',
    st_johnsbury: 'St. Johnsbury',
    sheffield: 'Sheffield',
    stannard: 'Stannard',
    sutton: 'Sutton',
    walden: 'Walden',
    waterford: 'Waterford',
    wheelock: 'Wheelock',
    bolton: 'Bolton',
    buels_gore: 'Buels Gore',
    burlington: 'Burlington',
    charlotte: 'Charlotte',
    colchester: 'Colchester',
    essex: 'Essex',
    hinesburg: 'Hinesburg',
    huntington: 'Huntington',
    jericho: 'Jericho',
    milton: 'Milton',
    richmond: 'Richmond',
    st_george: 'St. George',
    shelburne: 'Shelburne',
    south_burlington: 'South Burlington',
    underhill: 'Underhill',
    westford: 'Westford',
    williston: 'Williston',
    winooski: 'Winooski',
    averill: 'Averill',
    averys_gore: 'Avery\'s Gore',
    bloomfield: 'Bloomfield',
    brighton: 'Brighton',
    brunswick: 'Brunswick',
    canaan: 'Canaan',
    concord: 'Concord',
    east_haven: 'East Haven',
    ferdinand: 'Ferdinand',
    granby: 'Granby',
    guildhall: 'Guildhall',
    lemington: 'Lemington',
    lewis: 'Lewis',
    lunenburg: 'Lunenburg',
    maidstone: 'Maidstone',
    norton: 'Norton',
    victory: 'Victory',
    warners_grant: 'Warner\'s Grant',
    bakersfield: 'Bakersfield',
    berkshire: 'Berkshire',
    enosburg: 'Enosburg',
    fairfax: 'Fairfax',
    fairfield: 'Fairfield',
    fletcher: 'Fletcher',
    franklin: 'Franklin',
    georgia: 'Georgia',
    highgate: 'Highgate',
    montgomery: 'Montgomery',
    richford: 'Richford',
    st_albans_city: 'St. Albans City',
    st_albans_town: 'St. Albans Town',
    sheldon: 'Sheldon',
    swanton: 'Swanton',
    alburg: 'Alburg',
    grand_isle: 'Grand Isle',
    isle_la_motte: 'Isle La Motte',
    north_hero: 'North Hero',
    south_hero: 'South Hero',
    belvidere: 'Belvidere',
    cambridge: 'Cambridge',
    eden: 'Eden',
    elmore: 'Elmore',
    hyde_park: 'Hyde Park',
    johnson: 'Johnson',
    morristown: 'Morristown',
    stowe: 'Stowe',
    waterville: 'Waterville',
    wolcott: 'Wolcott',
    bradford: 'Bradford',
    braintree: 'Braintree',
    brookfield: 'Brookfield',
    chelsea: 'Chelsea',
    corinth: 'Corinth',
    fairlee: 'Fairlee',
    newbury: 'Newbury',
    orange: 'Orange',
    randolph: 'Randolph',
    strafford: 'Strafford',
    thetford: 'Thetford',
    topsham: 'Topsham',
    tunbridge: 'Tunbridge',
    vershire: 'Vershire',
    washington: 'Washington',
    west_fairlee: 'West Fairlee',
    williamstown: 'Williamstown',
    albany: 'Albany',
    barton: 'Barton',
    brownington: 'Brownington',
    charlestown: 'Charlestown',
    coventry: 'Coventry',
    craftsbury: 'Craftsbury',
    derby: 'Derby',
    glover: 'Glover',
    greensboro: 'Greensboro',
    holland: 'Holland',
    irasburg: 'Irasburg',
    jay: 'Jay',
    lowell: 'Lowell',
    morgan: 'Morgan',
    newport_city: 'Newport City',
    newport_town: 'Newport Town',
    troy: 'Troy',
    westfield: 'Westfield',
    westmore: 'Westmore',
    benson: 'Benson',
    brandon: 'Brandon',
    castleton: 'Castleton',
    chittenden: 'Chittenden',
    clarendon: 'Clarendon',
    danby: 'Danby',
    fair_haven: 'Fair Haven',
    hubbardton: 'Hubbardton',
    ira: 'Ira',
    killington: 'Killington',
    mendon: 'Mendon',
    middletown_springs: 'Middletown Springs',
    mount_holly: 'Mount Holly',
    mount_tabor: 'Mount Tabor',
    pawlet: 'Pawlet',
    pittsfield: 'Pittsfield',
    pittsford: 'Pittsford',
    poultney: 'Poultney',
    proctor: 'Proctor',
    rutland_city: 'Rutland City',
    rutland_town: 'Rutland Town',
    shrewsbury: 'Shrewsbury',
    sudbury: 'Sudbury',
    tinmouth: 'Tinmouth',
    wallingford: 'Wallingford',
    wells: 'Wells',
    west_haven: 'West Haven',
    west_rutland: 'West Rutland',
    barre_city: 'Barre City',
    barre_town: 'Barre Town',
    berlin: 'Berlin',
    cabot: 'Cabot',
    calais: 'Calais',
    duxbury: 'Duxbury',
    east_montpelier: 'East Montpelier',
    fayston: 'Fayston',
    marshfield: 'Marshfield',
    middlesex: 'Middlesex',
    montpelier: 'Montpelier',
    moretown: 'Moretown',
    northfield: 'Northfield',
    plainfield: 'Plainfield',
    roxbury: 'Roxbury',
    waitsfield: 'Waitsfield',
    warren: 'Warren',
    waterbury: 'Waterbury',
    woodbury: 'Woodbury',
    worcester: 'Worcester',
    athens: 'Athens',
    brattleboro: 'Brattleboro',
    brookline: 'Brookline',
    dover: 'Dover',
    dummerston: 'Dummerston',
    grafton: 'Grafton',
    guilford: 'Guilford',
    halifax: 'Halifax',
    jamaica: 'Jamaica',
    londonderry: 'Londonderry',
    marlboro: 'Marlboro',
    newfane: 'Newfane',
    putney: 'Putney',
    rockingham: 'Rockingham',
    somerset: 'Somerset',
    stratton: 'Stratton',
    townshend: 'Townshend',
    vernon: 'Vernon',
    wardsboro: 'Wardsboro',
    westminster: 'Westminster',
    whitingham: 'Whitingham',
    wilmington: 'Wilmington',
    windham: 'Windham',
    andover: 'Andover',
    baltimore: 'Baltimore',
    barnard: 'Barnard',
    bethel: 'Bethel',
    bridgewater: 'Bridgewater',
    cavendish: 'Cavendish',
    chester: 'Chester',
    hartford: 'Hartford',
    hartland: 'Hartland',
    ludlow: 'Ludlow',
    norwich: 'Norwich',
    plymouth: 'Plymouth',
    pomfret: 'Pomfret',
    reading: 'Reading',
    rochester: 'Rochester',
    royalton: 'Royalton',
    sharon: 'Sharon',
    springfield: 'Springfield',
    stockbridge: 'Stockbridge',
    weathersfield: 'Weathersfield',
    weston: 'Weston',
    west_windsor: 'West Windsor',
    windsor: 'Windsor',
    woodstock: 'Woodstock'
};
